# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVdzGVRatdJvm6fjv7jaQ6vakVvhxeG5
"""

checkerboard =[

[1, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0],

[0, 0, 0, 0, 0, 0, 0, 0]

]

def king(x1, y1, x2, y2):
  if (x1, y1) == (x2, y2):
    print("No")
    return

  if x2 < 0 or x2 > 7 or y2 < 0 or y2 > 7 or checkerboard[x2][y2] == 1:
    print("No")
    return

  if abs(x2 - x1) <= 1 and abs(y2 - y1) <= 1:
    print("Yes")
    return

  print("No")
  return

origin = input().split()
move = input().split()
x1, y1 = int(origin[0]), int(origin[1])
x2, y2 = int(move[0]), int(move[1])

king(x1, y1, x2, y2)