# -*- coding: utf-8 -*-
"""P1_1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1LVdzGVRatdJvm6fjv7jaQ6vakVvhxeG5
"""

origin = input().split()
move = input().split()
x_move = abs(int(origin[0]) - int(move[0]))
y_move = abs(int(origin[1]) - int(move[1]))
if x_move + y_move > 2 or x_move > 1 or y_move > 1:
  print("No")
elif x_move == 0 and y_move == 0:
  print("No")
elif checkerboard[int(move[0])][int(move[1])] == 1:
  print("No")
else:
  print("Yes")