# -*- coding: utf-8 -*-
"""P1_4.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1CYLQDevmrFqW7plGNf0LjoNaG5mKzN7w
"""

checkerboard =[ [1, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 1, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0],
  [0, 0, 0, 0, 0, 0, 0, 0] ]

origin = input().split()
move = input().split()
x1, y1 = int(origin[0]), int(origin[1])
x2, y2 = int(move[0]), int(move[1])

if (x1, y1) == (x2, y2):
  print("No")
  exit()

if x2 < 0 or x2 > 7 or y2 < 0 or y2 > 7 or checkerboard[x2][y2] == 1:
  print("No")
  exit()

# 檢查移動規則
if abs(x2 - x1) == 2 and abs(y2 - y1) == 1:
  print("Yes")
  exit()
elif abs(y2 - y1) == 2 and abs(x2 - x1) == 1:
  print("Yes")
  exit()
else:
  print("No")